apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: metrics-controller-manager
  name: controller-manager-metrics-service
  namespace: system
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  - name: custom-metrics
    targetPort: custom-metrics
    port: 443
  - name: keptn-metrics
    protocol: TCP
    port: 9999
    targetPort: keptn-metrics
  selector:
    control-plane: metrics-controller-manager
