# permissions for end users to edit keptnmetricproviders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keptnmetricprovider-editor-role
rules:
- apiGroups:
  - metrics.keptn.sh
  resources:
  - keptnmetricproviders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metrics.keptn.sh
  resources:
  - keptnmetricproviders/status
  verbs:
  - get
