apiVersion: metrics.keptn.sh/v1alpha1
kind: Metric
metadata:
  labels:
    app.kubernetes.io/name: metric
    app.kubernetes.io/instance: metric-sample
    app.kubernetes.io/part-of: metrics-operator
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: metrics-operator
  name: metric-sample
spec:
  # TODO(user): Add fields here
