# permissions for end users to edit keptnappcreationrequests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keptnappcreationrequest-editor-role
rules:
- apiGroups:
  - lifecycle.keptn.sh
  resources:
  - keptnappcreationrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lifecycle.keptn.sh
  resources:
  - keptnappcreationrequests/status
  verbs:
  - get
