# permissions for end users to view providers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: provider-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: metrics-operator
    app.kubernetes.io/part-of: metrics-operator
    app.kubernetes.io/managed-by: kustomize
  name: provider-viewer-role
rules:
- apiGroups:
  - metrics.keptn.sh
  resources:
  - providers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - metrics.keptn.sh
  resources:
  - providers/status
  verbs:
  - get
